In [1]:
import torch

In [3]:
# create tensor, 
t = torch.tensor([[2,4,6], [1,3,5]])
t

tensor([[2, 4, 6],
        [1, 3, 5]])

In [4]:
# # cheak size, 
t.shape

torch.Size([2, 3])

In [5]:
# no of dimensions in the tensor
t.ndim

2

In [11]:
transpose = t.t()
transpose

tensor([[2, 1],
        [4, 3],
        [6, 5]])

In [10]:
transpose.shape

torch.Size([3, 2])

In [14]:
# Create tensor of zeros
torch.zeros(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [31]:
# Numpy to torch tensor


import numpy as np

n = np.random.randn(1,10)
t = torch.from_numpy(n)

print(type(n))
print(type(t))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [34]:
# Autograd, 
from torch.autograd import Variable

a = torch.tensor([[2.5,4.3,5.0],[3.1,6.1,9.7]], requires_grad=True)
print(a)

tensor([[2.5000, 4.3000, 5.0000],
        [3.1000, 6.1000, 9.7000]], requires_grad=True)


In [35]:
y = torch.sum(a**3)
y

tensor(1389.5769, grad_fn=<SumBackward0>)

In [ ]:
y.backward()


In [39]:
a.grad.data

tensor([[ 18.7500,  55.4700,  75.0000],
        [ 28.8300, 111.6300, 282.2700]])