### Dataset Dataloader

In [2]:
import torch
from torch.utils.data import Dataset,DataLoader,TensorDataset

In [3]:
x = torch.arange(12, dtype=torch.float32)

In [4]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
data_loader = DataLoader(x, batch_size=4,shuffle=True)
data_loader

In [11]:
for data in data_loader:
    print(data)

tensor([ 7., 10.,  1.,  4.])
tensor([0., 2., 9., 5.])
tensor([ 3., 11.,  8.,  6.])


In [16]:
from sklearn.datasets import make_classification

x,y = make_classification(n_samples=10)


In [17]:
x.shape

(10, 20)

In [18]:
y.shape

(10,)

In [19]:
dataset = TensorDataset(torch.Tensor(x), torch.Tensor(y))

In [21]:
data_loader = DataLoader(dataset,batch_size=3, shuffle=True)
data_loader

In [22]:
for index,data in enumerate(data_loader):
    print(f'[{index}] : {data}')

[0] : [tensor([[ 0.7092, -0.4464, -0.9793, -1.6441,  1.0827,  0.8191, -0.3971,  0.5808,
         -0.5140, -0.9782, -1.3709, -0.0156,  1.2297, -0.8654, -1.9708, -0.2633,
         -0.0947,  0.7348,  0.3033,  0.7709],
        [ 0.6342,  0.8862, -0.5827, -2.2421, -0.1569, -1.5771, -0.5553, -0.7716,
          0.4308, -1.2789,  1.0776, -1.8341,  0.9784,  0.0779, -0.2081, -0.2253,
         -0.9102,  0.8384, -0.4900, -0.8613],
        [ 0.9574, -0.3610, -1.5313,  0.1258, -0.5666,  0.4959, -0.6513, -1.3308,
          1.7130,  0.6646, -1.2661,  0.0990,  0.8407, -0.2435, -0.7959,  0.1661,
         -0.6357,  0.5583, -1.1619, -0.3229]]), tensor([1., 1., 0.])]
[1] : [tensor([[-0.2965,  0.0385, -1.6419,  0.1392,  0.1847,  0.1211, -0.0355, -0.0281,
          0.2169,  1.0772,  1.6439, -0.5898, -0.1693, -1.3550, -1.0600,  0.1858,
          0.4770,  0.0173, -1.0466,  0.7880],
        [ 0.8361,  2.3427, -0.3444,  0.2330,  0.8701, -0.7660,  0.7728,  0.8145,
          1.0891,  0.6253, -0.1356,  1.3684,  0.2