# Fundamental of PyTorch

In [1]:
import torch

In [2]:
# Check Torch Version

torch.__version__

'2.2.1+cpu'

### Scaler

In [3]:
# scaler, 
scaler = torch.tensor(7)

In [12]:
print(f"Dimention of Scaler : {scaler.ndim}")
print(f"Item  of Scaler : {scaler.item()}")
print(f"Shape of Scaler : {scaler.shape}")
print(f"scaler : {scaler}")

Dimention of Scaler : 0
Item  of Scaler : 7
Shape of Scaler : torch.Size([])
scaler : 7


### Vector

In [10]:
vector = torch.tensor([2,4,5])

In [14]:
print(f"Dimention of vector : {vector.ndim}")
print(f"Shape of Vector : {vector.shape}")
print(f"Vector : {vector}")

Dimention of vector : 1
Shape of Vector : torch.Size([3])
Vector : tensor([2, 4, 5])


### Matrix

In [15]:
matrix = torch.tensor([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

In [18]:
print(f"Dimention of Matrix : {matrix.ndim}")
print(f"Shape of Matrix : {matrix.shape}")

Dimention of Matrix : 2
Shape of Matrix : torch.Size([3, 5])


### Tensor

In [23]:
tensor = torch.tensor([[
    [1,2,3],
    [3,4,5],
    [5,6,7],
    [7,8,9]
]])

In [21]:
print(f"Dimention of tensor : {tensor.ndim}")
print(f"Shape of tensor : {tensor.shape}")

Dimention of tensor : 3
Shape of tensor : torch.Size([1, 4, 3])


### random tensore, 

In [24]:
random_tensor = torch.rand(2,3)

In [27]:
print(f"Ramdom Tensor Data : {random_tensor}")
print(f"Shape : {random_tensor.shape}")
print(f"Data Type : {random_tensor.dtype}")

Ramdom Tensor Data : tensor([[0.9923, 0.7813, 0.0562],
        [0.2651, 0.0578, 0.8815]])
Shape : torch.Size([2, 3])
Data Type : torch.float32


### Zeros and ones

In [28]:
zeros_tensor = torch.zeros(3,4)

In [31]:
print(f"zeros_tensor : {zeros_tensor}")
print(f"Data Type : {zeros_tensor.dtype}")
print(f"Shape : {zeros_tensor.shape}")

zeros_tensor : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Data Type : torch.float32
Shape : torch.Size([3, 4])


In [32]:
one_tensor = torch.ones(4,5)

In [33]:
print(f"one_tensor : {one_tensor}")
print(f"Data Type : {one_tensor.dtype}")
print(f"Shape : {one_tensor.shape}")

one_tensor : tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Data Type : torch.float32
Shape : torch.Size([4, 5])


### Creating a range and tensors like

In [34]:
range_tensor = torch.range(start=1, end=100, step=9)

C:\Users\DELL\AppData\Local\Temp\ipykernel_14444\75295842.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(start=1, end=100, step=9)


In [37]:
print(f"Data : {range_tensor}")
print(f"Shape : {range_tensor.shape}")
print(f"Data Type ; {range_tensor.dtype}")

Data : tensor([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])
Shape : torch.Size([12])
Data Type ; torch.float32


### Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [39]:
tensorData = torch.tensor([1,2,3])

In [41]:
add1 = tensorData + 10
# or, 
add2 = torch.add(tensorData,10)

print(f"Add1 :{add1}")
print(f"Add2 : {add2}")


Add1 :tensor([11, 12, 13])
Add2 : tensor([11, 12, 13])


In [42]:
sub1 = tensorData-5
#or, 
sub2 = torch.sub(tensor,5)

print(f"Sub1 : {sub1}")
print(f"Sub2 : {sub2}")

Sub1 : tensor([-4, -3, -2])
Sub2 : tensor([-4, -3, -2])


In [43]:
mul1 = tensorData * 50.5
# or, 
mul2 = torch.mul(tensorData,50.5)

print(f"mul1 : {mul1}")
print(f"mul2 : {mul2}")

mul1 : tensor([ 50.5000, 101.0000, 151.5000])
mul2 : tensor([ 50.5000, 101.0000, 151.5000])


In [44]:
div1 = tensorData/10
# or, 
div2 = torch.div(tensorData,10)

print(f"div1 : {div1}")
print(f"div2 : {div2}")

div1 : tensor([0.1000, 0.2000, 0.3000])
div2 : tensor([0.1000, 0.2000, 0.3000])


### Matrix Multiplication

In [6]:
# create tensor, 

tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [9]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 2.01 ms


tensor(14)

In [13]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]], dtype=torch.float32)

tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]], dtype=torch.float32)

In [14]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

so, In this case we want to  matrix multiplication so we need apply transpose,

In [15]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76., 103.],
        [100., 136.]])

In [21]:
torch.manual_seed(40)

In [22]:
tensor = torch.tensor([10,20,30])

In [23]:
print(f'Argmax of the tensor : {torch.argmax(tensor)}')
print(f'Argmin of the tensor : {torch.argmin(tensor)}')

Argmax of the tensor : 2
Argmin of the tensor : 0


In [33]:
tensor = torch.arange(1,15)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
tensor_reshape = tensor.reshape(2,7)
tensor_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]])

In [5]:
import torch

x = torch.arange(1,8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [6]:
z= x
